security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            custom_authenticator:
                - App\Security\GoogleAuthenticator

            entry_point: form_login
            form_login:
                login_path: login
                check_path: login
                default_target_path: admin
            logout:
                path: /logout
                target: login
            login_throttling:
                max_attempts: 3
                interval: '15 minutes'

    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
